name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  train_and_register:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Training Script
        run: |
          python train3.py

      - name: Run Model Registration Script
        run: |
          python register_model.py
name: Train Titanic Model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        run: python src/train.py

